#!/bin/bash
###############################################################################

export CLICOLOR=1  # same as 'alias ls=ls -G' which I also have set
#export LSCOLORS=exfxcxdxbxegedabagacad

export LSCOLORS=gxfxcxdxbxegedabagacad

# Enable color in grep
export GREP_COLOR='3;33'

# History: don't store duplicates
export HISTCONTROL=erasedups
# History: 10,000 entries
export HISTSIZE=10000

alias mv='mv -i'
alias rm='rm -i'



# listing files
#alias la='ls -al'
#alias ltr='ls -ltr'
#alias lth='l -t|head'
alias lh='ls -Shl | less'
alias tf='tail -f -n 100'

# editing shortcuts
#alias m='mate'
alias vi='vim'
#alias sublime='open -a "/Applications/Sublime Text 2.app"'

# grep for a process
function psg {
  FIRST=`echo $1 | sed -e 's/^\(.\).*/\1/'`
  REST=`echo $1 | sed -e 's/^.\(.*\)/\1/'`
  ps aux | grep "[$FIRST]$REST"
}

# COLOR STRINGS
        RED="\[\033[0;31m\]"
     ORANGE="\[\033[0;33m\]"
     YELLOW="\[\033[0;33m\]"
      GREEN="\[\033[0;32m\]"
       BLUE="\[\033[0;34m\]"
  LIGHT_RED="\[\033[1;31m\]"
LIGHT_GREEN="\[\033[1;32m\]"
      WHITE="\[\033[1;37m\]"
 LIGHT_GRAY="\[\033[0;37m\]"
 COLOR_NONE="\[\e[0m\]"

function gitprompt () {
	local gitbranch=$(git branch 2>&1 | grep '\*' | sed -e 's/\* //g')
	if [[ "$gitbranch" != "" ]]; then
      PS1="${BLUE}\h${WHITE} [\u] ${LIGHT_GRAY}\w${YELLOW} (${gitbranch}) ${LIGHT_GRAY}: "
    else
      PS1="${BLUE}\h${WHITE} [\u] ${LIGHT_GRAY}\w${YELLOW} ${LIGHT_GRAY}: "
    fi
}
#PROMPT_COMMAND=gitprompt

shopt -s histverify

alias locate="find . -iname $1"
alias l='clear; ls -ltr'
alias la='clear; ls -ltra'
alias files='find . | less'
alias ext="find . -type f | sed -En 's|.*/[^/]+\.([^/.]+)$|\1|p' | sort -u"

alias h='history'
alias hg='history | grep $@'
alias rgi="rg --no-ignore"
alias rga='rg --no-ignore $@'
alias cls='clear'
alias codex='code -n .; exit;'

alias profile='vi ~/.tsm_profile'


function title {
    echo -ne "\033]0;"$*"\007"
}

alias untar='tar xvf'

# Easier navigation: .., ..., ...., ....., ~ and -
alias ..="cd .."
alias ...="cd ../.."
alias ....="cd ../../.."
alias .....="cd ../../../.."

alias cdr='cd $(git rev-parse --show-toplevel)'

export PATH=$PATH:~/Library/Python/3.7/bin
export PATH=$PATH:/home/tyson/.cargo/bin

source ~/.functions
source ~/.shortcuts.sh

cd ~